### ISSUE TITLE
Borough reference layers break chart

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-chart-view#106]
https://vis.crashmapper.org/?cfat=false&cinj=true&geo=city_council&mfat=false&minj=true&p1end=2018-10&p1start=2017-10&p2end=2017-10&p2start=2016-10&pfat=false&pinj=true&reference=bronx&trendAggMonths=1&view=trend

![image](https://user-images.githubusercontent.com/1423200/46504283-58229d80-c7e2-11e8-8513-23917ebbd490.png)

Some impact of adding borough names?

**Comment by gregallensworth** [comment]
Got it. The effect was when using a borough as the reference, since all areas have had their names "massages" to include borough names. In the case of borough names which don't get a prefix, they were still erroneously being given a single " " space as a prefix. As a result, they were not matched as reference areas by their proper name.

**Comment by gregallensworth** [comment]
Fixed and deployed two weeks ago.
